In [ ]:
import pandas as p

In [ ]:
d.head

<bound method NDFrame.head of                                                  title  \
0    Data Analysis Using R (Low Priced Edition): A ...
1    Head First Data Analysis: A learner's guide to...
2    Guerrilla Data Analysis Using Microsoft Excel:...
3    Python for Data Analysis: Data Wrangling with ...
4    Excel Data Analysis For Dummies (For Dummies (...
..                                                 ...
825   Deep Learning: Engage the World Change the World
826  Machine Learning in Finance: From Theory to Pr...
827  Practical Deep Learning at Scale with MLflow: ...
828  Clinical Biostatistics and Epidemiology Made R...
829  AI and Machine Learning for Coders: A Programm...

                                         author  price  \
0                           [ Dr Dhaval Maheta]   6.75
1                                           NaN  33.72
2            [ Oz du Soleil,  and , Bill Jelen]  32.07
3                           [ William McKinney]  53.99
4                             [ Paul McFedries]  24.49
..                                          ...    ...
825     [ Michael Fullan, Joanne Quinn, et al.]   5.33
826  [ Matthew F. Dixon, Igor Halperin, et al.]  55.18
827       [ Yong Liu,  and , Dr. Matei Zaharia]  44.99
828                                         NaN    NaN
829                         [ Laurence Moroney]  38.49

    price (including used books) pages  avg_reviews n_reviews star5 star4  \
0                           6.75   500          4.4        23   55%   39%
1                 21.49 - 33.72    484          4.3       124   61%   20%
2                          32.07   274          4.7        10   87%   13%
3                          53.99   547          4.6     1,686   75%   16%
4                          24.49   368          3.9        12   52%   17%
..                           ...   ...          ...       ...   ...   ...
825                8.55 - 35.33    208          4.5        74   72%   14%
826               52.41 - 55.18    573          4.5        93   78%    7%
827                        44.99   288          4.8         8   83%   17%
828                          NaN   NaN          NaN       NaN   NaN   NaN
829                        38.49   NaN          4.7       142   79%   15%

    star3 star2 star1                 dimensions       weight language  \
0      6%   NaN   NaN     8.5 x 1.01 x 11 inches  2.53 pounds  English
1      9%    4%    6%     8 x 0.98 x 9.25 inches  1.96 pounds  English
2     NaN   NaN   NaN  8.25 x 0.6 x 10.75 inches   1.4 pounds  English
3      5%    2%    2%     7 x 1.11 x 9.19 inches  1.47 pounds  English
4     10%   10%   10%  7.38 x 0.83 x 9.25 inches   1.3 pounds  English
..    ...   ...   ...                        ...          ...      ...
825    7%    2%    4%       7 x 0.47 x 10 inches  15.5 ounces  English
826    7%    4%    4%  6.14 x 1.25 x 9.21 inches  2.25 pounds  English
827   NaN   NaN   NaN   7.5 x 0.65 x 9.25 inches   1.1 pounds  English
828   NaN   NaN   NaN                        NaN          NaN      NaN
829    4%    1%    1%                        NaN          NaN      NaN

                                             publisher         ISBN_13  \
0       Notion Press Media Pvt Ltd (November 22, 2021)  978-1685549596
1        O'Reilly Media; 1st edition (August 18, 2009)  978-0596153939
2    Holy Macro! Books; Third edition (August 1, 2022)  978-1615470747
3      O'Reilly Media; 2nd edition (November 14, 2017)  978-1491957660
4          For Dummies; 5th edition (February 3, 2022)  978-1119844426
..                                                 ...             ...
825          Corwin; First edition (December 15, 2017)              59
826      Springer; 1st ed. 2020 edition (July 2, 2020)
827                    Packt Publishing (July 8, 2022)  978-1803241333
828                                                NaN             NaN
829                                                NaN

                                                  link  \
0    /Data-Analysis-Using-Low-Priced/dp/1685549594/...
1    /Head-First-Data-Analysis-statistics/dp/059615...
2    /Guerrilla-Analysis-Using-Microsoft-Excel/dp/1...
3    /Python-Data-Analysis-Wrangling-IPython/dp/149...
4    /Excel-Data-Analysis-Dummies-Computer/dp/11198...
..                                                 ...
825  /Deep-Learning-Engage-World-Change/dp/15063685...
826  /Machine-Learning-Finance-Theory-Practice/dp/3...
827  /gp/slredirect/picassoRedirect.html/ref=pa_sp_...
828  /Clinical-Biostatistics-Epidemiology-Ridiculou...
829  /Machine-Learning-Coders-Programmers-Intellige...

                                         complete_link
0    https://www.amazon.com/Data-Analysis-Using-Low...
1    https://www.amazon.com/Head-First-Data-Analysi...
2    https://www.amazon.com/Guerrilla-Analysis-Usin...
3    https://www.amazon.com/Python-Data-Analysis-Wr...
4    https://www.amazon.com/Excel-Data-Analysis-Dum...
..                                                 ...
825  https://www.amazon.com/Deep-Learning-Engage-Wo...
826  https://www.amazon.com/Machine-Learning-Financ...
827  https://www.amazon.com/gp/slredirect/picassoRe...
828  https://www.amazon.com/Clinical-Biostatistics-...
829  https://www.amazon.com/Machine-Learning-Coders...

[830 rows x 19 columns]>

In [ ]:
d.head()

,title,author,price,price (including used books),pages,avg_reviews,n_reviews,star5,star4,star3,star2,star1,dimensions,weight,language,publisher,ISBN_13,link,complete_link
0,Data Analysis Using R (Low Priced Edition): A ...,[ Dr Dhaval Maheta],6.75,6.75,500,4.4,23,55%,39%,6%,NaN,NaN,8.5 x 1.01 x 11 inches,2.53 pounds,English,"Notion Press Media Pvt Ltd (November 22, 2021)",978-1685549596,/Data-Analysis-Using-Low-Priced/dp/1685549594/...,https://www.amazon.com/Data-Analysis-Using-Low...
1,Head First Data Analysis: A learner's guide to...,NaN,33.72,21.49 - 33.72,484,4.3,124,61%,20%,9%,4%,6%,8 x 0.98 x 9.25 inches,1.96 pounds,English,"O'Reilly Media; 1st edition (August 18, 2009)",978-0596153939,/Head-First-Data-Analysis-statistics/dp/059615...,https://www.amazon.com/Head-First-Data-Analysi...
2,Guerrilla Data Analysis Using Microsoft Excel:...,"[ Oz du Soleil, and , Bill Jelen]",32.07,32.07,274,4.7,10,87%,13%,NaN,NaN,NaN,8.25 x 0.6 x 10.75 inches,1.4 pounds,English,"Holy Macro! Books; Third edition (August 1, 2022)",978-1615470747,/Guerrilla-Analysis-Using-Microsoft-Excel/dp/1...,https://www.amazon.com/Guerrilla-Analysis-Usin...
3,Python for Data Analysis: Data Wrangling with ...,[ William McKinney],53.99,53.99,547,4.6,"1,686",75%,16%,5%,2%,2%,7 x 1.11 x 9.19 inches,1.47 pounds,English,"O'Reilly Media; 2nd edition (November 14, 2017)",978-1491957660,/Python-Data-Analysis-Wrangling-IPython/dp/149...,https://www.amazon.com/Python-Data-Analysis-Wr...
4,Excel Data Analysis For Dummies (For Dummies (...,[ Paul McFedries],24.49,24.49,368,3.9,12,52%,17%,10%,10%,10%,7.38 x 0.83 x 9.25 inches,1.3 pounds,English,"For Dummies; 5th edition (February 3, 2022)",978-1119844426,/Excel-Data-Analysis-Dummies-Computer/dp/11198...,https://www.amazon.com/Excel-Data-Analysis-Dum...

In [ ]:
d.tail()

,title,author,price,price (including used books),pages,avg_reviews,n_reviews,star5,star4,star3,star2,star1,dimensions,weight,language,publisher,ISBN_13,link,complete_link
825,Deep Learning: Engage the World Change the World,"[ Michael Fullan, Joanne Quinn, et al.]",5.33,8.55 - 35.33,208,4.5,74,72%,14%,7%,2%,4%,7 x 0.47 x 10 inches,15.5 ounces,English,"Corwin; First edition (December 15, 2017)",59,/Deep-Learning-Engage-World-Change/dp/15063685...,https://www.amazon.com/Deep-Learning-Engage-Wo...
826,Machine Learning in Finance: From Theory to Pr...,"[ Matthew F. Dixon, Igor Halperin, et al.]",55.18,52.41 - 55.18,573,4.5,93,78%,7%,7%,4%,4%,6.14 x 1.25 x 9.21 inches,2.25 pounds,English,"Springer; 1st ed. 2020 edition (July 2, 2020)",,/Machine-Learning-Finance-Theory-Practice/dp/3...,https://www.amazon.com/Machine-Learning-Financ...
827,Practical Deep Learning at Scale with MLflow: ...,"[ Yong Liu, and , Dr. Matei Zaharia]",44.99,44.99,288,4.8,8,83%,17%,NaN,NaN,NaN,7.5 x 0.65 x 9.25 inches,1.1 pounds,English,"Packt Publishing (July 8, 2022)",978-1803241333,/gp/slredirect/picassoRedirect.html/ref=pa_sp_...,https://www.amazon.com/gp/slredirect/picassoRe...
828,Clinical Biostatistics and Epidemiology Made R...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Clinical-Biostatistics-Epidemiology-Ridiculou...,https://www.amazon.com/Clinical-Biostatistics-...
829,AI and Machine Learning for Coders: A Programm...,[ Laurence Moroney],38.49,38.49,NaN,4.7,142,79%,15%,4%,1%,1%,NaN,NaN,NaN,NaN,,/Machine-Learning-Coders-Programmers-Intellige...,https://www.amazon.com/Machine-Learning-Coders...

In [ ]:
d.shape()

TypeError: 'tuple' object is not callable

In [ ]:
d.shape

(830, 19)

In [ ]:
d.columns

Index(['title', 'author', 'price', 'price (including used books)', 'pages',
       'avg_reviews', 'n_reviews', 'star5', 'star4', 'star3', 'star2', 'star1',
       'dimensions', 'weight', 'language', 'publisher', 'ISBN_13', 'link',
       'complete_link'],
      dtype='object')

In [ ]:
d.iloc[5]

title                           Everything Data Analytics: A Beginner's Guide ...
author                                                                        NaN
price                                                                         NaN
price (including used books)                                                  NaN
pages                                                                         NaN
avg_reviews                                                                   4.2
n_reviews                                                                      31
star5                                                                         61%
star4                                                                         16%
star3                                                                         14%
star2                                                                          4%
star1                                                                          5%
dimensions                                                                    NaN
weight                                                                        NaN
language                                                                      NaN
publisher                                                                     NaN
ISBN_13                                                                       NaN
link                            /Everything-Data-Analytics-Beginners-Understan...
complete_link                   https://www.amazon.com/Everything-Data-Analyti...
Name: 5, dtype: object

In [ ]:
d.dtypes

title                            object
author                           object
price                           float64
price (including used books)     object
pages                            object
avg_reviews                     float64
n_reviews                        object
star5                            object
star4                            object
star3                            object
star2                            object
star1                            object
dimensions                       object
weight                           object
language                         object
publisher                        object
ISBN_13                          object
link                             object
complete_link                    object
dtype: object

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         830 non-null    object
 1   author                        657 non-null    object
 2   price                         722 non-null    float64
 3   price (including used books)  722 non-null    object
 4   pages                         745 non-null    object
 5   avg_reviews                   702 non-null    float64
 6   n_reviews                     702 non-null    object
 7   star5                         702 non-null    object
 8   star4                         635 non-null    object
 9   star3                         554 non-null    object
 10  star2                         451 non-null    object
 11  star1                         328 non-null    object
 12  dimensions                    644 non-null    object
 13  weight                        651 non-null    object
 14  language                      759 non-null    object
 15  publisher                     714 non-null    object
 16  ISBN_13                       665 non-null    object
 17  link                          830 non-null    object
 18  complete_link                 830 non-null    object
dtypes: float64(2), object(17)
memory usage: 123.3+ KB

In [ ]:
d.describe()

             price  avg_reviews
count   722.000000   702.000000
mean     46.491537     4.472080
std      63.292394     0.409608
min       0.990000     1.000000
25%      23.725000     4.325000
50%      39.490000     4.500000
75%      51.990000     4.700000
max    1318.740000     5.000000

In [ ]:
Y = d['price'][5]

In [ ]:
print(Y)

nan

In [ ]:
d['price'].iloc[5:10]

5      NaN
6    40.49
7    90.00
8    54.19
9    56.99
Name: price, dtype: float64

In [ ]:
d[['pages', 'author']].iloc[5]

pages     NaN
author    NaN
Name: 5, dtype: object

In [ ]:
d['new_col'] = d['price'] + d['height']

KeyError: 'height'

In [ ]:
d.columns

Index(['title', 'author', 'price', 'price (including used books)', 'pages',
       'avg_reviews', 'n_reviews', 'star5', 'star4', 'star3', 'star2', 'star1',
       'dimensions', 'weight', 'language', 'publisher', 'ISBN_13', 'link',
       'complete_link'],
      dtype='object')

In [ ]:
d['new_col'] = d['price'] + d['pages']

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [ ]:
d.columns

Index(['title', 'author', 'price', 'price (including used books)', 'pages',
       'avg_reviews', 'n_reviews', 'star5', 'star4', 'star3', 'star2', 'star1',
       'dimensions', 'weight', 'language', 'publisher', 'ISBN_13', 'link',
       'complete_link'],
      dtype='object')

In [ ]:
d['a'] = 5

In [ ]:
d[d['dimensions'] < 0.5]

TypeError: '<' not supported between instances of 'str' and 'float'

In [ ]:
import pandas as p

In [ ]:
d = p.read_csv('sample_data/random_data.csv')

In [ ]:
d = p.read_csv('sample_data/random_data.csv')

In [ ]:
d['new_col'] = d['Feature2'] + 5

In [ ]:
d[['Feature2']]

      Feature2
0     0.797417
1     0.026838
2     0.199990
3     0.474124
4     0.598516
...        ...
4995  0.819440
4996  0.032140
4997  0.263300
4998  0.640986
4999  0.901570

[5000 rows x 1 columns]

In [ ]:
d[d['Feature2'] < 0.5]

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,...,Feature12,Feature13,Feature14,Feature15,Feature16,Feature17,Feature18,Feature19,Feature20,new_col
1,47.0,0.026838,-0.244178,D,NaN,NaN,2.151535,0.450312,-3.395356,NaN,...,X,0,Category1,Option2,NaN,13.355832,Yes,Low,cat,5.026838
2,64.0,0.199990,-1.014799,B,0.0,474.0,1.410613,6.786555,-3.070746,NaN,...,Z,0,Category1,Option2,NaN,13.449484,Yes,Medium,dog,5.199990
3,67.0,0.474124,0.448040,B,NaN,166.0,0.635091,1.937158,-0.246269,6.004975,...,X,0,Category1,Option2,NaN,7.687652,Yes,Low,cat,5.474124
11,NaN,0.087169,-0.293628,A,0.0,587.0,2.428588,3.271965,0.972953,NaN,...,Y,0,Category1,Option3,NaN,12.457649,Yes,Medium,some other,5.087169
12,88.0,0.329888,0.245180,NaN,NaN,NaN,0.814215,8.156511,-1.317728,NaN,...,Z,0,Category1,Option3,NaN,6.294401,Yes,Medium,NaN,5.329888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4987,4.0,0.011676,1.152884,A,0.0,127.0,0.088079,1.869545,3.603783,NaN,...,Y,0,Category1,Option3,NaN,11.930489,Yes,Medium,cat,5.011676
4992,42.0,0.271165,0.021821,C,NaN,NaN,0.947761,3.370658,-0.960625,NaN,...,Y,0,Category3,Option2,NaN,5.370457,Yes,Low,NaN,5.271165
4993,84.0,0.091607,-1.366911,D,NaN,705.0,1.673878,5.855658,-0.636449,NaN,...,Z,0,Category1,Option1,9.249976,8.508937,Yes,Medium,dog,5.091607
4996,NaN,0.032140,-1.445420,C,1.0,NaN,0.806246,8.765315,-1.866815,NaN,...,Y,0,Category3,Option4,6.368173,5.308922,Yes,Medium,NaN,5.032140
4997,92.0,0.263300,0.986722,C,NaN,78.0,1.326853,4.489722,1.720671,6.877962,...,X,0,Category1,Option4,5.682022,9.508951,Yes,Medium,NaN,5.263300

In [ ]:
a = d[d['Feature2'] < 0.5]

In [ ]:
a

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,...,Feature12,Feature13,Feature14,Feature15,Feature16,Feature17,Feature18,Feature19,Feature20,new_col
1,47.0,0.026838,-0.244178,D,NaN,NaN,2.151535,0.450312,-3.395356,NaN,...,X,0,Category1,Option2,NaN,13.355832,Yes,Low,cat,5.026838
2,64.0,0.199990,-1.014799,B,0.0,474.0,1.410613,6.786555,-3.070746,NaN,...,Z,0,Category1,Option2,NaN,13.449484,Yes,Medium,dog,5.199990
3,67.0,0.474124,0.448040,B,NaN,166.0,0.635091,1.937158,-0.246269,6.004975,...,X,0,Category1,Option2,NaN,7.687652,Yes,Low,cat,5.474124
11,NaN,0.087169,-0.293628,A,0.0,587.0,2.428588,3.271965,0.972953,NaN,...,Y,0,Category1,Option3,NaN,12.457649,Yes,Medium,some other,5.087169
12,88.0,0.329888,0.245180,NaN,NaN,NaN,0.814215,8.156511,-1.317728,NaN,...,Z,0,Category1,Option3,NaN,6.294401,Yes,Medium,NaN,5.329888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4987,4.0,0.011676,1.152884,A,0.0,127.0,0.088079,1.869545,3.603783,NaN,...,Y,0,Category1,Option3,NaN,11.930489,Yes,Medium,cat,5.011676
4992,42.0,0.271165,0.021821,C,NaN,NaN,0.947761,3.370658,-0.960625,NaN,...,Y,0,Category3,Option2,NaN,5.370457,Yes,Low,NaN,5.271165
4993,84.0,0.091607,-1.366911,D,NaN,705.0,1.673878,5.855658,-0.636449,NaN,...,Z,0,Category1,Option1,9.249976,8.508937,Yes,Medium,dog,5.091607
4996,NaN,0.032140,-1.445420,C,1.0,NaN,0.806246,8.765315,-1.866815,NaN,...,Y,0,Category3,Option4,6.368173,5.308922,Yes,Medium,NaN,5.032140
4997,92.0,0.263300,0.986722,C,NaN,78.0,1.326853,4.489722,1.720671,6.877962,...,X,0,Category1,Option4,5.682022,9.508951,Yes,Medium,NaN,5.263300

In [ ]:
d[(d['Feature2'] < 0.5) & (d['Feature3'] > 0)]

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,...,Feature12,Feature13,Feature14,Feature15,Feature16,Feature17,Feature18,Feature19,Feature20,new_col
3,67.0,0.474124,0.448040,B,NaN,166.000000,0.635091,1.937158,-0.246269,6.004975,...,X,0,Category1,Option2,NaN,7.687652,Yes,Low,cat,5.474124
12,88.0,0.329888,0.245180,NaN,NaN,NaN,0.814215,8.156511,-1.317728,NaN,...,Z,0,Category1,Option3,NaN,6.294401,Yes,Medium,NaN,5.329888
16,NaN,0.196474,0.983773,NaN,NaN,734.000000,0.483883,3.609294,1.196249,6.093364,...,X,0,Category1,Option4,12.719932,8.054799,No,Medium,cat,5.196474
21,NaN,0.397841,0.248413,NaN,NaN,375.494983,0.881802,6.783169,-0.558243,6.057295,...,Y,1,Category2,Option1,9.121466,9.983985,No,High,NaN,5.397841
33,NaN,0.221392,0.475404,NaN,0.0,NaN,0.110751,2.882430,-4.647367,NaN,...,X,0,Category1,Option1,11.305325,7.430412,No,High,dog,5.221392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4983,NaN,0.245673,1.273752,B,0.0,133.000000,1.245834,3.300026,-0.131068,NaN,...,Z,0,Category3,Option4,10.862303,8.754387,Yes,Medium,dog,5.245673
4985,NaN,0.418488,0.231568,C,NaN,NaN,2.615529,2.806550,0.551236,NaN,...,Y,0,Category1,Option1,10.370324,10.658936,Yes,Medium,dog,5.418488
4987,4.0,0.011676,1.152884,A,0.0,127.000000,0.088079,1.869545,3.603783,NaN,...,Y,0,Category1,Option3,NaN,11.930489,Yes,Medium,cat,5.011676
4992,42.0,0.271165,0.021821,C,NaN,NaN,0.947761,3.370658,-0.960625,NaN,...,Y,0,Category3,Option2,NaN,5.370457,Yes,Low,NaN,5.271165
4997,92.0,0.263300,0.986722,C,NaN,78.000000,1.326853,4.489722,1.720671,6.877962,...,X,0,Category1,Option4,5.682022,9.508951,Yes,Medium,NaN,5.263300

In [ ]:
d[d['Feature2'] > d['Feature3']]

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,...,Feature12,Feature13,Feature14,Feature15,Feature16,Feature17,Feature18,Feature19,Feature20,new_col
0,44.0,0.797417,-0.958091,NaN,NaN,158.0,1.490148,5.166124,2.277942,NaN,...,X,1,Category1,Option4,8.824345,11.711130,Yes,Low,NaN,5.797417
1,47.0,0.026838,-0.244178,D,NaN,NaN,2.151535,0.450312,-3.395356,NaN,...,X,0,Category1,Option2,NaN,13.355832,Yes,Low,cat,5.026838
2,64.0,0.199990,-1.014799,B,0.0,474.0,1.410613,6.786555,-3.070746,NaN,...,Z,0,Category1,Option2,NaN,13.449484,Yes,Medium,dog,5.199990
3,67.0,0.474124,0.448040,B,NaN,166.0,0.635091,1.937158,-0.246269,6.004975,...,X,0,Category1,Option2,NaN,7.687652,Yes,Low,cat,5.474124
4,NaN,0.598516,0.087839,NaN,0.0,NaN,0.392104,4.010937,3.215086,2.891199,...,Z,0,Category1,Option3,11.259371,6.807770,Yes,Low,cat,5.598516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,84.0,0.091607,-1.366911,D,NaN,705.0,1.673878,5.855658,-0.636449,NaN,...,Z,0,Category1,Option1,9.249976,8.508937,Yes,Medium,dog,5.091607
4994,NaN,0.635389,-1.115966,NaN,NaN,NaN,0.050992,1.970292,1.298545,NaN,...,Z,1,Category1,Option2,14.308017,14.873926,Yes,Low,dog,5.635389
4995,NaN,0.819440,0.415931,C,0.0,NaN,1.765590,1.929735,-1.951884,NaN,...,Z,1,Category2,Option4,NaN,14.821501,No,Low,NaN,5.819440
4996,NaN,0.032140,-1.445420,C,1.0,NaN,0.806246,8.765315,-1.866815,NaN,...,Y,0,Category3,Option4,6.368173,5.308922,Yes,Medium,NaN,5.032140
4998,91.0,0.640986,-1.199847,A,0.0,51.0,0.312256,2.773963,-3.320704,6.138322,...,X,0,Category1,Option3,4.574748,8.705127,No,Medium,some other,5.640986

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Feature1   2296 non-null   float64
 1   Feature2   5000 non-null   float64
 2   Feature3   5000 non-null   float64
 3   Feature4   3132 non-null   object
 4   Feature5   2968 non-null   float64
 5   Feature6   3016 non-null   float64
 6   Feature7   5000 non-null   float64
 7   Feature8   4899 non-null   float64
 8   Feature9   5000 non-null   float64
 9   Feature10  2164 non-null   float64
 10  Feature11  5000 non-null   int64
 11  Feature12  5000 non-null   object
 12  Feature13  5000 non-null   int64
 13  Feature14  5000 non-null   object
 14  Feature15  5000 non-null   object
 15  Feature16  2994 non-null   float64
 16  Feature17  5000 non-null   float64
 17  Feature18  5000 non-null   object
 18  Feature19  4705 non-null   object
 19  Feature20  3267 non-null   object
 20  new_col    5000 non-null   float64
dtypes: float64(12), int64(2), object(7)
memory usage: 820.4+ KB

In [ ]:
d.select_dtypes(include=['object'])

     Feature4 Feature12  Feature14 Feature15 Feature18 Feature19   Feature20
0         NaN         X  Category1   Option4       Yes       Low         NaN
1           D         X  Category1   Option2       Yes       Low         cat
2           B         Z  Category1   Option2       Yes    Medium         dog
3           B         X  Category1   Option2       Yes       Low         cat
4         NaN         Z  Category1   Option3       Yes       Low         cat
...       ...       ...        ...       ...       ...       ...         ...
4995        C         Z  Category2   Option4        No       Low         NaN
4996        C         Y  Category3   Option4       Yes    Medium         NaN
4997        C         X  Category1   Option4       Yes    Medium         NaN
4998        A         X  Category1   Option3        No    Medium  some other
4999      NaN         X  Category2   Option2       Yes      High  some other

[5000 rows x 7 columns]

In [ ]:
d.isnull().sum()

Feature1     2704
Feature2        0
Feature3        0
Feature4     1868
Feature5     2032
Feature6     1984
Feature7        0
Feature8      101
Feature9        0
Feature10    2836
Feature11       0
Feature12       0
Feature13       0
Feature14       0
Feature15       0
Feature16    2006
Feature17       0
Feature18       0
Feature19     295
Feature20    1733
new_col         0
dtype: int64

In [ ]:
d.notnull().sum()

Feature1     2296
Feature2     5000
Feature3     5000
Feature4     3132
Feature5     2968
Feature6     3016
Feature7     5000
Feature8     4899
Feature9     5000
Feature10    2164
Feature11    5000
Feature12    5000
Feature13    5000
Feature14    5000
Feature15    5000
Feature16    2994
Feature17    5000
Feature18    5000
Feature19    4705
Feature20    3267
new_col      5000
dtype: int64

In [ ]:
d.dropna()

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,...,Feature12,Feature13,Feature14,Feature15,Feature16,Feature17,Feature18,Feature19,Feature20,new_col
171,95.0,0.703015,0.588349,A,0.0,202.0,4.277223,0.538676,-0.589273,6.842019,...,X,1,Category2,Option4,8.111158,5.480642,No,High,dog,5.703015
209,54.0,0.933366,-1.032108,D,0.0,203.0,1.213096,3.858360,-0.858259,6.103829,...,Y,0,Category1,Option1,8.350913,10.656313,No,High,dog,5.933366
232,10.0,0.340107,-0.188947,C,0.0,715.0,4.862813,2.203301,-2.543057,3.005423,...,Z,0,Category2,Option4,8.996658,5.908967,No,Medium,dog,5.340107
343,51.0,0.724042,0.326311,B,1.0,110.0,1.784348,3.798955,-0.650484,5.004120,...,Y,0,Category1,Option3,9.793357,6.262076,Yes,High,dog,5.724042
531,71.0,0.067583,-2.938568,B,0.0,545.0,1.358502,3.681450,4.859383,5.878888,...,Z,0,Category3,Option1,9.671996,7.048327,No,High,some other,5.067583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4800,0.0,0.849989,0.302729,C,1.0,171.0,0.113641,2.519976,1.457208,4.091374,...,Z,1,Category2,Option4,9.098511,13.142023,Yes,Low,cat,5.849989
4814,41.0,0.458115,0.958438,C,0.0,113.0,5.252798,1.646902,-0.078289,3.888032,...,Z,0,Category3,Option2,9.952264,9.996767,Yes,Low,some other,5.458115
4957,29.0,0.790611,-1.156629,D,0.0,83.0,2.282176,1.459783,1.056873,4.935896,...,X,1,Category1,Option3,8.249298,6.908584,No,Low,dog,5.790611
4962,56.0,0.271911,-0.517786,B,0.0,51.0,0.022858,2.442092,1.240329,10.039921,...,Z,1,Category2,Option2,11.508433,7.176284,Yes,Medium,cat,5.271911
4998,91.0,0.640986,-1.199847,A,0.0,51.0,0.312256,2.773963,-3.320704,6.138322,...,X,0,Category1,Option3,4.574748,8.705127,No,Medium,some other,5.640986

In [ ]:
d.fillna(0)

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,...,Feature12,Feature13,Feature14,Feature15,Feature16,Feature17,Feature18,Feature19,Feature20,new_col
0,44.0,0.797417,-0.958091,0,0.0,158.0,1.490148,5.166124,2.277942,0.000000,...,X,1,Category1,Option4,8.824345,11.711130,Yes,Low,0,5.797417
1,47.0,0.026838,-0.244178,D,0.0,0.0,2.151535,0.450312,-3.395356,0.000000,...,X,0,Category1,Option2,0.000000,13.355832,Yes,Low,cat,5.026838
2,64.0,0.199990,-1.014799,B,0.0,474.0,1.410613,6.786555,-3.070746,0.000000,...,Z,0,Category1,Option2,0.000000,13.449484,Yes,Medium,dog,5.199990
3,67.0,0.474124,0.448040,B,0.0,166.0,0.635091,1.937158,-0.246269,6.004975,...,X,0,Category1,Option2,0.000000,7.687652,Yes,Low,cat,5.474124
4,0.0,0.598516,0.087839,0,0.0,0.0,0.392104,4.010937,3.215086,2.891199,...,Z,0,Category1,Option3,11.259371,6.807770,Yes,Low,cat,5.598516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.0,0.819440,0.415931,C,0.0,0.0,1.765590,1.929735,-1.951884,0.000000,...,Z,1,Category2,Option4,0.000000,14.821501,No,Low,0,5.819440
4996,0.0,0.032140,-1.445420,C,1.0,0.0,0.806246,8.765315,-1.866815,0.000000,...,Y,0,Category3,Option4,6.368173,5.308922,Yes,Medium,0,5.032140
4997,92.0,0.263300,0.986722,C,0.0,78.0,1.326853,4.489722,1.720671,6.877962,...,X,0,Category1,Option4,5.682022,9.508951,Yes,Medium,0,5.263300
4998,91.0,0.640986,-1.199847,A,0.0,51.0,0.312256,2.773963,-3.320704,6.138322,...,X,0,Category1,Option3,4.574748,8.705127,No,Medium,some other,5.640986
4999,0.0,0.901570,1.836382,0,0.0,0.0,2.087461,6.854886,-0.259228,6.068139,...,X,0,Category2,Option2,12.801075,14.686372,Yes,High,some other,5.901570

In [ ]:
d['Feature4'].replace({'D':'C','B':'A'})

0       NaN
1         C
2         A
3         A
4       NaN
       ...
4995      C
4996      C
4997      C
4998      A
4999    NaN
Name: Feature4, Length: 5000, dtype: object